### ISSUE TITLE
Battle Fade Out?

### ISSUE THREAD

**Issue by SerialConvort** [KC3Kai/KC3Kai#826]
First time putting in issues I find and not sure on the details, but is the Battle Tab for KC3Kai supposed to be this faded out? I remember it being more bold in earlier versions. https://gyazo.com/a4b1415f40503ed4275f0f34b4c09224

**Comment by SerialConvort** [comment]
This was during my usual Orel 2-3 runs, I have run the same map twice and refreshed and the problem still persists albeit the battle tab still works fine, its just that its kinda faded out.

**Comment by ethrundr** [comment]
First thing first, which version are you using right now.
And if it's dev build, please give us the latest checksum in your report to let us know which build you are using right now :)

**Comment by SerialConvort** [comment]
DevKC3Kai, I don't know how to checksum.

![](https://i.gyazo.com/bf3e6114fd33ba4d67a351a89eaf6844.png)

![](https://i.gyazo.com/196bf629aa4870d8ff2106d187a22226.jpg)

**Comment by SerialConvort** [comment]
Clicked that by accident, sorry.

**Comment by ethrundr** [comment]
the development should has ID `mpbmijbpaidcombbkjalbfloocoopafh` AFAIK....

also are you using the GitHub client on your desktop? if yes, just click the latest commit you have there, and see the hex number beside the poster, it's the checksum.

**Comment by ReiFan49** [comment]
development ID is unique actually...

**Comment by ethrundr** [comment]
well not experienced with the chrome setting, so yeah....

however I believe this issue has been solved somewhere before....

**Comment by SerialConvort** [comment]
Er is this it 

![](https://i.gyazo.com/0e2e56a36d3c3ff007e5c80f568bf71f.png)

**Comment by ethrundr** [comment]
hmm... you're on b2c1bfd, so it should be pretty much almost up-to-date

@bamboo3250 @dragonjet @McDohl any idea with this?

**Comment by bamboo3250** [comment]
@SerialConvort you are on `dev-subtitle` branch. You try switching the branch back to `master` on b93d2cd05584f12f67ccec42e821425b77ffb12e then reload KC3Kai and see if the problem still persists or not.

**Comment by SerialConvort** [comment]
Refreshed after going back to master, problem still persists.

![](https://i.gyazo.com/4765d322313a0b7cc8ec6ab750b02a9c.png)

**Comment by bamboo3250** [comment]
I'm on the same commit, using the same fleet but it doesn't happen to me. Perhaps it's because of the KC3Kai Settings?

![screen shot 2015-09-11 at 3 17 58 pm](https://cloud.githubusercontent.com/assets/8078323/9809159/86e05494-5898-11e5-9472-0adc72688456.png)

**Comment by SerialConvort** [comment]
I do not know the cause nor can I find it at the top of my head. Ill try checking in again tomorrow after I sleep now, but the problem still persists even after I refresh for some reason, and I checked another map, 1-1, the problem is pretty much on every map I have tested so far and I just started using DevKC3Kai, so this version should be the newest.

![](https://i.gyazo.com/8a554390d11b462d4bcab5d0692f6d8d.png)
.

**Comment by ReiFan49** [comment]
can you inspect the panel?

**Comment by nekoworkshop** [comment]
Here is what I got when going to 1-1 with b93d2cd05584f12f67ccec42e821425b77ffb12e . Besides the mask like color , battle prediction didn't work for the first node.
![1](https://cloud.githubusercontent.com/assets/1346257/9809671/60600ac2-5838-11e5-87e8-3078a7573b9a.PNG)
![2342](https://cloud.githubusercontent.com/assets/1346257/9809673/636af556-5838-11e5-82b6-054bb5236f0f.PNG)

@ReiFan49 I've been trying to find a way to do element inspect on the panel. If you could enlighten me that would be awesome.

Gotta hit the hay before sunrise...

**Comment by ethrundr** [comment]
The simplest way to open the Inspection tool is to detach the panel. Then you can simplu navigate to the panel and press F12 there. 

After the inspection tool shows up, do this:
- Navigate to the Console tab (usually accessible by shortcut Ctrl+8)
- Reproduce the error
- When an error notification on console appears (shaded in red), copy the error message (or snip it) to here :)

**Comment by nekoworkshop** [comment]
@ethrundr By saying panel I mean the KC3Kai interface not the browser tab holding the swf. Sorry for the confusion.
Strange thing is I see no error during the entire sortie.

**Comment by bamboo3250** [comment]
@SerialConvort @nekoworkshop Could you guys take a screenshot of KC3Kai Settings page? I suspect it is the source of problem.

**Comment by nekoworkshop** [comment]
@bamboo3250 I'll look into this tomorrow. Really need to get some sleep now...

**Comment by dragonjet** [comment]
ah I think I know this. @SerialConvort the `dev-subtitle` branch it truly broken. and just doing a checkout to master will not fix it. you'll need to reload the extension XD

**Comment by ethrundr** [comment]
@nekoworkshop yes I know that, and I'm talking about the KC3kai interface here XD

**Comment by ReiFan49** [comment]
@nekoworkshop 
1. hold the [--] or [ | ] icon besides the close icon on panel
2. select the detached window icon
3. press any inspection key (<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>I</kbd>/<kbd>J</kbd> or others) on the detached panel
4. voile, another window shows up, it's inspecting the current panel (auto-close if you close the panel)

**Comment by nekoworkshop** [comment]
Bonjour.
@ReiFan49 Thanks for the tips. Just figured out that I have to use the inspection key to create the second developer tools window. Simply detach the first one and press F12 as @ethrundr suggested will close it instead of creating a new one ( Probably it will work on OS X but I've got a Windows box :/).

Pulled the latest master image 9d7b072df094fbca8767c48c64fc20a41ced3cbe and still able to reproduce the problem. Here are the errors in console.

![image](https://cloud.githubusercontent.com/assets/1346257/9816742/c821b4a6-586c-11e5-82d7-b0255e2e2e9b.png)

Getting "unexpected token u" when doing JSON parsing usually means that the data to be parsed is not defined.

Here is my localstorage. 
![image](https://cloud.githubusercontent.com/assets/1346257/9816933/fab014de-586d-11e5-83c2-fae5e3bd1c00.png)
Got any idea why there is missing something ?

**Comment by dragonjet** [comment]
have you done the `submodule update` after pulling the latest?

**Comment by nekoworkshop** [comment]
Didn't run the command but looks like SmartGit took care of it. I can see all those files in there so it should be alright, I assume?
![image](https://cloud.githubusercontent.com/assets/1346257/9817211/7c6a394a-586f-11e5-8588-f4628adc6689.png)

**Comment by dragonjet** [comment]
ah I think that will work now

**Comment by nekoworkshop** [comment]
Here is what I found.

The problem is due to KC3 being unable to read localStorage.maps thus stalled the whole code block for battle predition. As you can see from my previous post the localstorage.maps is missing from my local storage. I searched the code for the initialization code for localStorage.maps but found nothing
![image](https://cloud.githubusercontent.com/assets/1346257/9827268/92876d58-58ae-11e5-81b5-faf586c67155.png)

The map data is supposed to be populated when the API response of api_get_member/mapinfo arrives. There was a line of code to initialize it but it was removed in a patch few days ago.
https://github.com/KC3Kai/KC3Kai/commit/eb9dd2a6d81940e3bec0615862a8f6f5a8ffabfd#diff-2181f73accfb84cded588cf6ad5e6212L829

After I put back `var maps = {};` the problem is gone.
![image](https://cloud.githubusercontent.com/assets/1346257/9827461/4d8b72f6-58b0-11e5-832c-485ba1f5835e.png)

@ReiFan49 Could you look into the code and fix it? I believe there's a reason why you added the `var maps = JSON.parse(localStorage.maps);`

**Comment by dragonjet** [comment]
ah so for those who doesn't have `localStorage.maps` yet, the `JSON.parse` kills it, thus not finishing `api_get_member/mapinfo`. So when the battle comes, there's no map info as you said, stopping before prediction, etc. Did I get it right? xD

**Comment by nekoworkshop** [comment]
You got it.

**Comment by ReiFan49** [comment]
$.extend({},JSON.parse(localStorage.maps) might fix it?

**Comment by dragonjet** [comment]
I think this is a critical bug which needs a webstore release of its own, `19.3`

We might need to branch out or the `webstore` branch to add this fix, just so that the breaking features of v20 on master wouldn't be included

and yes we could also use `$.extend` for those with event maps on their local storage, which are now gone on the new mapinfo

**Comment by SerialConvort** [comment]
Ok gotcha, so should I just keep this thread open or..?

**Comment by ReiFan49** [comment]
keep it until there's a push that fixes this issue

**Comment by SerialConvort** [comment]
Kk

**Comment by dragonjet** [comment]
oh I'd like to mention it here, @KC3Kai/developers you may assign yourself if going to work on an issue, just so that there won't be duplicate fixes
